program     = (var_decl | func_decl)+
var_decl    = IDENT IDENT ";"
func_decl   = IDENT IDENT "(" param ("," param)* ")" "{" statement* "}"
param       = IDENT IDENT
block       = "{" statement* "}"
statement   = if
            | while
            | call
if          = "if" "(" expr ")" block ";"
while       = "while" "(" expr ")" block ";"
call        = IDENT "(" expr ("," expr)* ")" ";"
expr        = unary (op unary)?
unary       = IDENT
            | INT
            | STRING
            | "&" IDENT
            | "(" expr ")"
op          = "+" | "-" | "&" | "|" | "^" | "<<" | ">>"
            | "==" | "!=" | "<" | ">" | "<=" | ">="
