program   = (var_decl | func_decl)+
var_decl  = type IDENT ";"
func_decl = type IDENT "(" param ("," param)* ")" (";" | block)
param     = type IDENT
type      = IDENT "*"?
block     = "{" statement* "}"
statement = if | call | return
if        = "if" "(" expr ")" block ";"
call      = IDENT "(" expr ("," expr)* ")" ";"
return    = "return" expr ";"
expr      = unary (op unary)?
unary     = IDENT
          | INT
          | STRING
          | "&" IDENT
          | "(" expr ")"
op        = "+" | "-" | "&" | "|" | "^" | "<<" | ">>"
          | "==" | "!=" | "<" | ">" | "<=" | ">="
